### ISSUE TITLE
Vaadin 8 

### ISSUE THREAD

**Issue by selimok** [Artur-/spring-boot-loaded-vaadin#2]
Hi @Artur-,

thanks for this good example. It works very good with vaadin 7. But not with vaadin8. Do you have any idea, how to achieve that? 

Thanks in advice.

Kind Regards,
Selim

**Comment by Artur-** [comment]
What is the problem you are seeing when using Vaadin 8? I have not had time to test it but I can't see anything obvious which would cause problems except #1

**Comment by selimok** [comment]
Hi @Artur- ,

I got following exceptions,

```
java.lang.RuntimeException: Push failed
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:171) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:146) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.ui.UI.push(UI.java:1594) ~[vaadin-server-8.0.0.jar:8.0.0]
	at org.vaadin.artur.AutoReloadUI.push(AutoReloadUI.java) ~[classes/:na]
	at org.vaadin.artur.MyUI.push(MyUI.java) ~[classes/:na]
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1009) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1851) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1817) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1392) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.ui.UI.access(UI.java:1487) ~[vaadin-server-8.0.0.jar:8.0.0]
	at org.vaadin.artur.AutoReloadUI.access(AutoReloadUI.java) ~[classes/:na]
	at org.vaadin.artur.MyUI.access(MyUI.java) ~[classes/:na]
	at org.vaadin.artur.AutoReloadUI.reloadEvent(AutoReloadUI.java:20) ~[classes/:na]
	at org.vaadin.artur.MyUI.reloadEvent(MyUI.java) ~[classes/:na]
	at org.springsource.loaded.TypeRegistry.fireReloadEvent(TypeRegistry.java:2026) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:444) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:1018) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:251) [springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:235) [springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.IllegalStateException: The type registry TypeRegistry(id=1961303491,loader=sun.misc.Launcher$AppClassLoader) does not know about type id 749
	at org.springsource.loaded.TypeRegistry.getReloadableType(TypeRegistry.java:1910) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1789) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at com.vaadin.server.communication.LegacyUidlWriter.sortByHierarchy(LegacyUidlWriter.java:91) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:71) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:141) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:168) ~[vaadin-server-8.0.0.jar:8.0.0]
	... 20 common frames omitted

2017-04-24 22:12:28.993 ERROR 7445 --- [Loader@14dad5dc] org.springsource.loaded.agent.Watcher    : FileWatcher caught serious error, see cause

java.lang.RuntimeException: Push failed
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:171) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:146) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.ui.UI.push(UI.java:1594) ~[vaadin-server-8.0.0.jar:8.0.0]
	at org.vaadin.artur.AutoReloadUI.push(AutoReloadUI.java) ~[classes/:na]
	at org.vaadin.artur.MyUI.push(MyUI.java) ~[classes/:na]
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1009) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1851) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1817) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1392) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.ui.UI.access(UI.java:1487) ~[vaadin-server-8.0.0.jar:8.0.0]
	at org.vaadin.artur.AutoReloadUI.access(AutoReloadUI.java) ~[classes/:na]
	at org.vaadin.artur.MyUI.access(MyUI.java) ~[classes/:na]
	at org.vaadin.artur.AutoReloadUI.reloadEvent(AutoReloadUI.java:20) ~[classes/:na]
	at org.vaadin.artur.MyUI.reloadEvent(MyUI.java) ~[classes/:na]
	at org.springsource.loaded.TypeRegistry.fireReloadEvent(TypeRegistry.java:2026) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:444) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:1018) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:251) [springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:235) [springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.IllegalStateException: The type registry TypeRegistry(id=1961303491,loader=sun.misc.Launcher$AppClassLoader) does not know about type id 749
	at org.springsource.loaded.TypeRegistry.getReloadableType(TypeRegistry.java:1910) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1789) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at com.vaadin.server.communication.LegacyUidlWriter.sortByHierarchy(LegacyUidlWriter.java:91) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:71) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:141) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:168) ~[vaadin-server-8.0.0.jar:8.0.0]
	... 20 common frames omitted
```

Any Idea?

Thanks.

**Comment by selimok** [comment]
Oh, it might be a problem with spring-loaded. It seems to be a compatibility problem with Java 8. See
https://github.com/spring-projects/spring-loaded/issues/165

**Comment by selimok** [comment]
Problem resolved in springloaded version 1.2.8.BUILD-SNAPSHOT .

Thanks for your time.
